// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQ8HHpiVeaK0VYU0IeHyk3NSujqq29Vk',
    appId: '1:870207661094:web:4b9f34e20216b9122cf2e7',
    messagingSenderId: '870207661094',
    projectId: 'calculator-incognito',
    authDomain: 'calculator-incognito.firebaseapp.com',
    storageBucket: 'calculator-incognito.firebasestorage.app',
    measurementId: 'G-JE2ZNQEVPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARy4OmbOHYuZhO93M6Rli_4-Td95clIF4',
    appId: '1:870207661094:android:f81017d91ca323652cf2e7',
    messagingSenderId: '870207661094',
    projectId: 'calculator-incognito',
    storageBucket: 'calculator-incognito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBooMmtF3xHbN4muTaI58jiHDPxy6LiRcA',
    appId: '1:870207661094:ios:401a1586144ff7be2cf2e7',
    messagingSenderId: '870207661094',
    projectId: 'calculator-incognito',
    storageBucket: 'calculator-incognito.firebasestorage.app',
    iosBundleId: 'com.calculator.dev.prod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyQ8HHpiVeaK0VYU0IeHyk3NSujqq29Vk',
    appId: '1:870207661094:web:db5f15e4c1636c582cf2e7',
    messagingSenderId: '870207661094',
    projectId: 'calculator-incognito',
    authDomain: 'calculator-incognito.firebaseapp.com',
    storageBucket: 'calculator-incognito.firebasestorage.app',
    measurementId: 'G-4C5S3PDEF5',
  );
}
